### ISSUE TITLE
Unmapped responses?

### ISSUE THREAD

**Issue by rexlow** [truework/gretchen#12]
Hi there! This project sounds promising and thanks for the good work!

I am trying out gretchen with a newly spun-up react project (v16.12.0) and was not able to get any response data.

**Environment**

- react: v16.12.0
- gretchen: v1.1.2

**Code Snippet**
```
  useEffect(() => {
    (async() => {
      console.log(await gretch("https://reqres.in/api/products/3").json())
    })();
  })
```

**Result**
The network debugger shows there is indeed data return from the mock server but it is not mapped to the response? Tried with `fetch` and it works fine. Experimented with different versions `1.11.0` and `1.11.1` and it is still the same.

<img width="855" alt="Screenshot 2020-05-26 at 2 40 38 PM" src="https://user-images.githubusercontent.com/7680796/82868256-df47fa80-9f5e-11ea-8e1e-5e6428e42933.png">

**Comment by estrattonbailey** [comment]
@rexlow sorry about this, you're right on the money. We were previously doing a check for `Content-Length` before parsing, however, this isn't a required header and is sometimes stripped in cross-origin requests.

I've removed this and [published as a pre-release](https://github.com/truework/gretchen/releases/tag/v1.2.0-0), just run `npm i gretchen@next --save`. Would you mind giving that a go and let me know if it works for you?

I'll do some testing too. If all is well then I'll publish as v1.2.0.

**Comment by estrattonbailey** [comment]
Looks good to me at the moment, running the reqres.in call from Chrome console.

**Comment by rexlow** [comment]
I have verified that `v1.2.0` is working correctly now. Thanks for the swift response!
