### ISSUE TITLE
Strongly typed request body?

### ISSUE THREAD

**Issue by mildfuzz** [truework/gretchen#21]
I'm looking for a solution to typing fetch, and Gretchen looked to be a good fit, but it stops short of typing the request body. Any reason?

**Comment by estrattonbailey** [comment]
Hey 👋  better late than never 😄 I get what you're saying, idk why I didn't before, sorry about that.

I tend to think typing the props passed to the `json` prop should probably live in user-land. Right now the `gretch` method simply accepts `<Response, ErrorResponse>` types. Adding in other options like request body, headers, etc, would bloat this, and probably require a major version bump, which I don't think we want to do right now.

How I've handled this in the past, as you probably have too, is to wrap the fetcher in another function that serves as a type guard:

```typescript
// types are checked when calling createPost(...)
export function createPost({ title, body }: { title: string, body: string}) {
  return gretch('...', {
    method: 'PUT',
    json: {
      title,
      body,
    }
  })
}
```

Guessing you've moved on at this point 😆 so I'll close this, but feel free to continue the convo.
