### ISSUE TITLE
Path to cjs build is incorrect (v1.4.0)

### ISSUE THREAD

**Issue by anantoghosh** [truework/gretchen#24]
![image](https://user-images.githubusercontent.com/12339068/124255333-e553c780-dade-11eb-9b87-2d8b18bd989a.png)

The **main** path, there is no file `grentchen.cjs.js`.

This has caused jest to fail which depend on cjs modules.

---
Otherwise, a great project. 👍

**Comment by estrattonbailey** [comment]
Sorry for the LONG delay. This was fixed with f4211e5b171f63116ed1f07c98f671dfcd225fff 👍
